In [1]:
import cv2
import matplotlib.pyplot as plt 
import numpy as np

In [7]:
lkparams = dict(winSize = (200,200),maxLevel=2,criteria=(cv2.TERM_CRITERIA_EPS | cv2.TERM_CRITERIA_COUNT , 10,0.03))
cs = cv2.CascadeClassifier('DATA/haarcascades/haarcascade_frontalface_default.xml')
cap = cv2.VideoCapture(0)
ret,prevframe = cap.read()
face = prevframe.copy()
def detect(img):
    face = img.copy()
    rect = cs.detectMultiScale(face)
   # print(rect.ravel())
    for(x,y,w,h) in rect:
        pp = [[[x,y]],[[x+w,y]],[[x,y+h]],[[x+w,y+h]]]
        cv2.rectangle(face,(x,y),(x+w,y+h),(255,0,0),10)
    return pp
prev_gray = cv2.cvtColor(prevframe,cv2.COLOR_BGR2GRAY)
prevp = detect(prevframe)
prevpts = np.array(prevp,dtype= np.float32)
print(prevpts)
mask = np.zeros_like(prevframe)
while True:
    ret2, frame = cap.read() 
    frame_gray = cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    nextpts,status,err = cv2.calcOpticalFlowPyrLK(prev_gray,frame_gray,prevpts,None,**lkparams)
    good_new = nextpts[status==1]
    good_prev = prevpts[status==1]
    for i ,(new,prev ) in enumerate(zip(good_new,good_prev)):
        x_new,y_new = new.ravel()
        x_prev,y_prev = new.ravel()
        mask = cv2.line(mask ,(x_new,y_new),(x_prev,y_prev),(0,0,255),6)
        frame = cv2.circle(frame, (x_new,y_new),8,(0,255,0),-1)
    img = cv2.add(frame,mask)
    cv2.imshow('op',img)
    prev_gray = frame_gray.copy()
    prevpts = good_new.reshape(-1,1,2)
    if cv2.waitKey(1) & 0XFF==27:
        break
cap.release()        
cv2.destroyAllWindows() 


[[[276. 215.]]

 [[423. 215.]]

 [[276. 362.]]

 [[423. 362.]]]
